// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CartSuite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('BeerTest', async function() {
    // Test name: BeerTest
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 3 | assertText | css=tr:nth-child(4) > .ng-binding | €2.00
    // 1x RoboBeer = €2.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€2.00")
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €4.00
    // 2x RoboBeer = €4.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€4.00")
  })
  it('ColaTest', async function() {
    // Test name: ColaTest
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 3 | assertText | css=tr:nth-child(4) > .ng-binding | €1.25
    // 1x RobaCola = €1.25
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€1.25")
    // 4 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €2.50
    // 2x RobaCola = €2.50
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€2.50")
  })
  it('WineTest', async function() {
    // Test name: WineTest
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | click | css=.ng-scope:nth-child(3) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) > td .input-group-append > .btn")).click()
    // 3 | assertText | css=tr:nth-child(4) > .ng-binding | €3.00
    // 1x RobWine = €3.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€3.00")
    // 4 | click | css=.ng-scope:nth-child(3) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) > td .input-group-append > .btn")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €6.00
    // 2x RobWine = €6.00
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€6.00")
  })
})

